# Generated by Django 6.0.4 on 2026-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('HR_ADMIN', 'HR Admin'), ('HIRING_MANAGER', 'Hiring_Manager'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', max_length=20),
        ),
    ]
