# Generated by Django 6.0.4 on 2026-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('HR_ADMIN', 'HR Admin'), ('HIRING_MANAGER', 'Hiring Manager'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', max_length=20),
        ),
    ]
