# Generated by Django 6.0.4 on 2026-05-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('INTERVIEWER', 'Interviewer'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', max_length=20),
        ),
    ]
