# Generated by Django 6.0.4 on 2026-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
