# Generated by Django 6.0.4 on 2026-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_profile_company_name_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
