# Generated by Django 6.0.4 on 2026-05-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_room_participants(apps, schema_editor):
    ChatRoom = apps.get_model('chat', 'ChatRoom')

    for room in ChatRoom.objects.select_related(
        'candidate',
        'interviewer',
        'interview__hr_name',
        'interview__application__job__created_by',
    ):
        hr_user_id = (
            room.interview.hr_name_id
            or room.interview.application.job.created_by_id
        )
        participants = [
            hr_user_id,
        ]

        if room.room_type == 'candidate':
            participants.append(room.candidate_id)
        elif room.room_type == 'interviewer':
            participants.append(room.interviewer_id)
        elif room.room_type == 'group':
            participants.extend([room.candidate_id, room.interviewer_id])

        room.participants.add(*[user_id for user_id in participants if user_id])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_room_name_and_more'),
        ('interviews', '0006_alter_interview_interviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('candidate', 'HR to Candidate'), ('interviewer', 'HR to Interviewer'), ('group', 'Group Chat')], default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='interviews.interview'),
        ),
        migrations.RunPython(copy_existing_room_participants, noop_reverse),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('interview', 'room_type')},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='interviewer',
        ),
    ]
