# Generated by Django 6.0.4 on 2026-06-29 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_replace_old_chat_with_private_rooms'),
        ('interviews', '0006_alter_interview_interviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='interview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='interviews.interview'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('interview', 'user1', 'user2')},
        ),
    ]
