# Generated by Django 6.0.4 on 2026-05-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_approved',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
