# Generated by Django 6.0.4 on 2026-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_is_approved_company_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
