# Generated by Django 6.0.4 on 2026-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_decision_note_interview_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SHEDULED', 'Sheduled'), ('COMPLETED', 'Completed'), ('SHORT_LISTED', 'Short listed'), ('CANCELLED', 'Cancelled')], default='SHEDULED', max_length=20),
        ),
    ]
