# Generated by Django 6.0.4 on 2026-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
