# Generated by Django 6.0.4 on 2026-06-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
