# Generated by Django 6.0.4 on 2026-06-10 06:31

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.application_resume_path),
        ),
    ]
