# Generated by Django 6.0.4 on 2026-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
