# Generated by Django 6.0.4 on 2026-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_company_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On Site'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=20),
        ),
    ]
