# Generated by Django 6.0.4 on 2026-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_job_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
