# Generated by Django 6.0.4 on 2026-06-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_expiry_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='expiry_at',
            new_name='expires_at',
        ),
    ]
