# Generated by Django 6.0.4 on 2026-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_expiry_at_job_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
